### ISSUE TITLE
Shortcut for current file in directives?

### ISSUE THREAD

**Issue by LindyBalboa** [islandoftex/arara#110]
Hi, first thanks for the nice tool. I have to be honest, it took a day of tinkering to really understand how it works, but the power is fantastic!

So I wrote a python script to convert 4 spaces (tabs) inside `easylist` environments to the appropriate symbols. This helps keep my source clean and readable while have the option to view it as a list or as a paragraph. I'm trying to use this workflow to structure the sub-ideas of my paragraphs better.

It works as intended, but I see room for improvement. Currently my pre-processing script directive is
`% arara: python: {script: whitespace_easylist_tex.py, inputfile: the_current_file.tex}`

with `python.yaml`
```
!config
# python rule for arara
# author: Conenr Phillips 
# requires arara 3.0+
identifier: python
name: python
commands:
- name: latex easylist macro python script
  command: <arara> python @{script} @{inputfile} @{options}
arguments:
- identifier: script
  flag: <arara> @{parameters.script}
- identifier: inputfile
  flag: <arara> @{parameters.inputfile}
- identifier: options
  flag: <arara> @{parameters.options}
```

I have copied this into each file for my chapters. As it stands, I had to manually replace the name for "this file" in each one. 

**The Question:** are there variables for use inside directives? I use vim and would find it super useful to just use `%` or something like `@%` as a general specifier for the current file. Is something like this possible and I just missed it?

**Comment by cereda** [comment]
Hello, friend!

Thank you very much for the kind words! :wink: 

First and foremost, I would like to ask which version of `arara` you are using. By the looks of your rule, it seems the upcoming version 4.0 (to be officially released in a few days). Sorry for question, but I just want to be sure. :wink: 

Very interesting script, congratulations!

**Comment by cereda** [comment]
I just wrote a nice `python.yaml` rule for version 4.0, but I just want to be sure. :wink:

**Comment by LindyBalboa** [comment]
Yes, I am indeed using the latest 4.0. I run arch Linux and tend to use a
lot of git packages.

Paulo Cereda <notifications@github.com> schrieb am Mo., 2. Juli 2018, 19:50:

**Comment by LindyBalboa** [comment]
Actually, I realize now my original post doesn't highlight the problem. It is easy enough to just use the `@{file}` orb in the python rule. Where the problem comes into play is after my python script renames the file, because I want to preserve the unmodified original. So then what this looks like in the directives is:

```
% arara: python: {script: whitespace_easylist_tex.py}
% arara: pdflatex: {options: ["-jobname=original_file"], files: [easylist_original_file.tex]}
```

if instead I could do something like the following, that would be very cool.

```
% arara: python: {script: whitespace_easylist_tex.py}
% arara: pdflatex: {options: ["-jobname="<%>], files: [easylist_<%>.tex]}
```

Maybe I am missing an easier solution, but that is why I am reaching out for help.

**Comment by cereda** [comment]
Hello! :wink: 

Answering your question, in version 4.0 there is no parameter evaluation in the directive scope. The actual proper processing should happen at the rule scope. The original idea is to simply forward raw values to the rule and let it decide what do to with them. I sketched the directive concept below, for illustrative purposes:

![Quack](https://user-images.githubusercontent.com/302062/42269649-1847e07e-7f55-11e8-8379-97b86bdb00f0.png)

Technically, the only processing happening at the directive level is what we call _directive conditional_ (or simply _conditional_ for short), which consists of a special keyword and a boolean expression which dictate whether and how the associated directive should be considered. Still, the directive itself is kept untouched.

We can add parameter evaluation in the directive scope as a potential new feature for either a maintenance version (still in the 4 series) or a major release (in the 5.0 branch, yet to be created). I like challenges. :wink: 

For that end, I might need to summon the team. It is a good idea to have a preliminary discussion on this feature, as it may have significant implications in existing rules. I have some ideas for new features as well, so we can add one more to the proverbial bucket of ideas. :wink: 

That's the official answer, I guess. In other news, would you mind if I give you some ideas and enhancements to your rule? They are listed in the manual, but since it is not officially released, only a few people (four, I guess) know about such suggestions. :wink: 

All the best!

**Comment by cereda** [comment]
Hi!

_First and foremost, deeply sorry for the delay in replying to you. The last days were quite hectic and I still have some personal issues to solve at the moment._

I wrote the following Python rule. It is not exactly what you were originally looking for, but I guess it shows some interesting features of the new version which could be useful for your future scripts:

```yaml
!config
identifier: python
name: Python
commands:
- name: The Python interpreter
  command: >
    @{
        return getCommand(interpreter, options, script, input);
    }
arguments:
- identifier: script
  flag: >
    @{
        parameters.script
    }
  required: true
- identifier: input
  flag: >
    @{
        parameters.input
    }
- identifier: options
  flag: >
    @{
        if (isList(parameters.options)) {
            return parameters.options;
        }
        else {
            throwError('I was expecting a list of options.');
        }
    }
- identifier: interpreter
  flag: >
    @{
        parameters.interpreter
    }
  default: python
```

Let us break down the rule and I will try to comment the most significant changes:

```yaml
!config
identifier: python
name: Python
commands:
- name: The Python interpreter
```

So far, so good, I guess. :wink: 

```yaml
  command: >
    @{
        return getCommand(interpreter, options, script, input);
    }
```

I replaced the plain string call to a `Command` object. System commands in plain string usually work, but there are situations in which the parser fails to separate "who is who" in it. As a means to provide a better way of defining system commands, this method was introduced. In here, we explicitly tell the parts of our system commands, from the executable to the arguments. Some notes:

1. Lists are flattened, so `[ 1, [ 2, 3 ], [ [ 4, [ 5 ] ], 6 ]` will become `[ 1, 2, 3, 4, 5, 6 ]`. This is useful if you want to pass e.g, command line options directly to your script or even Python interpreter.

2. Empty strings are discarded, so `getCommand('ls', '', '-l', '-a', '')` will become `ls` + `-l` + `-a` when the elements are normalized. So, if a rule argument resolves to an empty string, it will simply be discarded when the command is being build.

```yaml
arguments:
- identifier: script
  flag: >
    @{
        parameters.script
    }
```

It is simply a writing style. :wink: From version 4.0 on, I am adopting the folded style for writing scalars, but the one line version is also valid. I like the "more verbose" way because it gives me a clearer view of what is happening in the rule.

```yaml
  required: true
```

I added a `required` key (version 4.0 feature) which means the user _must_ provide it when using the corresponding directive in the source code. I think it makes sense as the Python interpreter must have an associated script.

```
- identifier: input
  flag: >
    @{
        parameters.input
    }
```

As the name indicates (or probably not), the `input` key refers to the input elements of our Python script. I would like to exploit the dynamic typing of the underlying scripting language used by `arara`, so we can simply use

```tex
% arara: python: { script: myscript.py, input: foo }
```

or

```tex
% arara: python: { script: myscript.py, input: [ foo ] }
```

which will be handled later on by the `getCommand` method. The idea behind this is that if your script requires more than one argument, we can provide them as a proper list in the directive, e.g,

```tex
% arara: python: { script: myscript.py, input: [ 1, 2, 3 ] }
```

Let us continue with the new rule. :wink: 

```yaml
- identifier: options
  flag: >
    @{
        if (isList(parameters.options)) {
            return parameters.options;
        }
        else {
            throwError('I was expecting a list of options.');
        }
    }
```

The `options` key here was moved before the `script` key in the `getCommand` line because I wanted to use it as potential interpreter options. I don't know much Python, but maybe a flag or two might be important in some scenarios. In this case, `options` has to be a list, otherwise the tool will throw an error about it.

```yaml
- identifier: interpreter
  flag: >
    @{
        parameters.interpreter
    }
  default: python
```

I added an argument named `interpreter` in case one needs to invoke other interpreters, e.g, Python 3 instead of Python 2, for the script. The default value relies on `python`.

And that's it. :wink: 

Your idea of shortcuts in directives is a very interesting feature to be considered in the near future. I will discuss with the team a way of providing it. For now, thank you very much for this idea! I will keep you informed of our progress, hopefully in the development branch (which does not exist yet, but that will be fixed any time soon).

All the best!

**Comment by TheTeXnician** [comment]
This did not make it to version 5.0. We got quite a number of feature-requests to enable more control and interaction in the directive scope and as we are considering to change rule format in version 6 again, there might be some progress. But this is only a long-term goal, sorry.

**Comment by TheTeXnician** [comment]
> Actually, I realize now my original post doesn't highlight the problem. It is easy enough to just use the `@{file}` orb in the python rule. Where the problem comes into play is after my python script renames the file, because I want to preserve the unmodified original. So then what this looks like in the directives is:
> 
> ```
> % arara: python: {script: whitespace_easylist_tex.py}
> % arara: pdflatex: {options: ["-jobname=original_file"], files: [easylist_original_file.tex]}
> ```
> 
> if instead I could do something like the following, that would be very cool.
> 
> ```
> % arara: python: {script: whitespace_easylist_tex.py}
> % arara: pdflatex: {options: ["-jobname="<%>], files: [easylist_<%>.tex]}
> ```
> 
> Maybe I am missing an easier solution, but that is why I am reaching out for help.

As of ececdcca9ef8612b7ed5e1ef657b34bc2b41a41f you can use orb tags like the following (see also https://gitlab.com/islandoftex/arara/-/issues/38#note_416717294):

```
% arara: python: {script: whitespace_easylist_tex.py}
% arara: pdflatex: {options: ["-jobname=@{getOriginalReference().getName()}"]}
```

But this expansion will only happen within the `options` parameter. You cannot use it in `files` and we will not implement it in that way. This expansion process will be shipped with version 6 in TL 2021.

Due to the thorough discussions of the matter in the team, we will close that issue with the new release. Everything else should be encapsulated into rule logic where one may use proper file moving and more.

**Comment by TheTeXnician** [comment]
arara v6 has been released and will make its way to CTAN within the next days.
