### ISSUE TITLE
Move arara log file to another directory

### ISSUE THREAD

**Issue by ashirwad** [islandoftex/arara#133]
Hello,

Is it possible to move arara log file to another directory? I desire this behavior as I typically use an output directory called `build` to hold all the regeneratable files. This allows me to keep the main directory tidy.

Thanks!

**Comment by cereda** [comment]
Hi!

Thank you very much for your feedback! It is an interesting idea and certainly a new feature for the upcoming version.

I decided to investigate what could be realistically done in the current version 4.0 branch. Sadly, the proposal was way trickier than I originally thought. My first course of action was to provide a rule and directive that would move `arara.log` to a new location, say,

```tex
% arara: log: { directory: build }
```

However, it would not be of any help for us since `arara` closes the log file stream _after_ all directives had been interpreted. By the time the `log` directive would be interpreted, `arara.log` would not exist yet, so there would be nothing available to be moved.

Back to the drawing board. Then I thought I could exploit a certain key in the configuration file that holds the log name:

```yaml
logname: 'build/arara'
```

Then `arara` would append the `.log` extension _et voilà_, problem solved! However, for some reason, my past self had implemented some sort of path normalization in this key value, so only the last part of the path (i.e, `arara`) is considered.

So, it's not possible, given the current state of affairs. However, I kindly ask you to wait a bit for me to inspect the code. Maybe I could circumvent this restriction by implementing either another key or removing the normalization in the log name. I will keep you updated on my progress.

For now, I am deeply sorry for this feature not being possible at the moment... :cry:

**Comment by ashirwad** [comment]
Thank you so much for giving this feature a serious thought! I will wait to hear back on your progress. :)

**Comment by TheTeXnician** [comment]
From 7753190c6703d1be19818329888f30587d4a4355 on, arara supports specifying a path for the log name. This change will be shipped in arara v6 which will be included in TeX Live 2021.

**Comment by TheTeXnician** [comment]
arara v6 has been released and will make its way to CTAN within the next days.
